[tox]
; py3.7 runs into aiocoap unrelated trouble in setups on Debian sid, leaving
; this to `setup.py test` for now
;
; For uvloop not being tested with pyp3, see
; https://github.com/chrysn/aiocoap/issues/193.
envlist = {py37,py38,py39,pypy3}-{noextras,allextras},py38-uvloop

[testenv]
deps =
    coverage

commands =
    python -m coverage run --parallel -m aiocoap.cli.defaults
    python -m coverage run --parallel -m unittest discover -v

[testenv:{py37,py38,py39,pypy3}-noextras]
description = Running on plain Python

[testenv:{py37,py38,py39,pypy3}-allextras]
description = Running with all extra dependencies installed
extras =
    all

setenv =
    AIOCOAP_DEFAULTS_EXPECT_ALL=1

[testenv:{py38,pypy3}-uvloop]
description = Running on uvloop
deps =
    coverage
    uvloop
extras =
    all
; client-/server-transport could just as well be done on the default main loop,
; but AFAIR uvloop required occasional workarounds
setenv =
    AIOCOAP_TESTS_LOOP=uvloop
    AIOCOAP_CLIENT_TRANSPORT=oscore:simple6
    AIOCOAP_SERVER_TRANSPORT=oscore:simplesocketserver
